<a href="https://colab.research.google.com/github/rajeevfromkrec/pytorch/blob/master/Linear_regression_in_py_torch_practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [66]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [3]:
import numpy as np
import torch

In [67]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [68]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)

In [69]:
def model(x):
  return x@w.t()+b

In [70]:
preds=model(inputs)

In [71]:
preds

tensor([[154.8217, 212.3058],
        [202.0205, 279.5202],
        [227.3845, 332.2667],
        [167.0313, 207.8248],
        [186.1890, 270.2977]], grad_fn=<AddBackward0>)

In [72]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [73]:
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff**2)/diff.numel()

In [74]:
loss=mse(targets,preds)
loss

tensor(20801.3086, grad_fn=<DivBackward0>)

In [75]:
loss.backward()

In [79]:
w.grad

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [77]:
b.grad


tensor([111.2894, 168.4430])

In [78]:
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [84]:
print(loss)

tensor(20801.3086, grad_fn=<DivBackward0>)


In [83]:
print(w.grad)

None


In [82]:
for i in range(100):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w= w  - w.grad * 1e-5
    b= b  - b.grad * 1e-5
    b.grad.zero_()
    w.grad.zero_()

AttributeError: ignored

In [55]:
# Adjust weights & reset gradients
preds=model(inputs)
loss=mse(preds,targets)
loss.backward()



In [56]:
print(w.grad)

None


In [85]:
import torch.nn as nn

In [86]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')


In [87]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [88]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [89]:
from torch.utils.data import TensorDataset

In [90]:
train_ds=TensorDataset(inputs,targets)

In [92]:
type(train_ds)

torch.utils.data.dataset.TensorDataset

In [94]:
train_ds[:]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [95]:
from torch.utils.data import DataLoader

In [96]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [97]:
model=nn.Linear(3,2)

In [98]:
print(model.weight)

Parameter containing:
tensor([[-0.4121, -0.4831, -0.0427],
        [ 0.2153,  0.1191,  0.3401]], requires_grad=True)


In [103]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4121, -0.4831, -0.0427],
         [ 0.2153,  0.1191,  0.3401]], requires_grad=True),
 Parameter containing:
 tensor([-0.3092, -0.2825], requires_grad=True)]

In [104]:
preds=model(inputs)

In [105]:
preds

tensor([[ -64.5949,   38.0335],
        [ -83.0545,   51.5508],
        [-103.3704,   54.1266],
        [ -64.6956,   39.3773],
        [ -78.1095,   49.8085],
        [ -64.5949,   38.0335],
        [ -83.0545,   51.5508],
        [-103.3704,   54.1266],
        [ -64.6956,   39.3773],
        [ -78.1095,   49.8085],
        [ -64.5949,   38.0335],
        [ -83.0545,   51.5508],
        [-103.3704,   54.1266],
        [ -64.6956,   39.3773],
        [ -78.1095,   49.8085]], grad_fn=<AddmmBackward>)

In [106]:
import torch.nn.functional as F

In [107]:
loss_fn=F.mse_loss

In [108]:
loss =loss_fn(preds,targets)

In [109]:
loss

tensor(14570.3594, grad_fn=<MseLossBackward>)

In [110]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [113]:
def fit(num_epochs,model,loss_fn,opt,train_dl):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred=model(xb)
      loss=loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
      if (epoch+1%10)==0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))


In [114]:
fit(100,model,loss_fn,opt,train_dl)

In [115]:
preds=model(inputs)

In [116]:
preds

tensor([[ 58.4001,  71.6056],
        [ 82.2667,  99.6069],
        [117.4189, 133.9559],
        [ 27.8046,  44.1040],
        [ 97.9795, 113.0473],
        [ 58.4001,  71.6056],
        [ 82.2667,  99.6069],
        [117.4189, 133.9559],
        [ 27.8046,  44.1040],
        [ 97.9795, 113.0473],
        [ 58.4001,  71.6056],
        [ 82.2667,  99.6069],
        [117.4189, 133.9559],
        [ 27.8046,  44.1040],
        [ 97.9795, 113.0473]], grad_fn=<AddmmBackward>)